### PR TITLE
Multiple small improvements

### PR DESCRIPTION
**Pull request by helmo**

### CODE REVIEW

**Comment by omega8cc** [comment]
Thanks for the PR!

as for the `symlinks -dr` however, it doesn't translate to `--domain --revoke`, it is just a forced cleanup to delete any broken symlinks:

```
quad:~# symlinks --help
symlinks: scan/change symbolic links - v1.3 - by Mark Lord

Usage:  symlinks [-cdorstv] dirlist

Flags:  -c == change absolute/messy links to relative
    -d == delete dangling links
    -o == warn about links across file systems
    -r == recurse into subdirs
    -s == shorten lengthy links (displayed in output only when -c not specified)
    -t == show what would be done by -c
    -v == verbose (show all symlinks)

quad:~#
```

**Comment by omega8cc** [comment]
How to reproduce the issue related to "Skip empty alt_names"? The `$alt_names` never carries any value, it is only a `TRUE`/`FALSE` flag.

**Comment by omega8cc** [comment]
Ah, I have confused `$alt_names` with `$no_alt_names` in this commit :)

**Comment by omega8cc** [comment]
Also, I have enabled "Issues" in this project, which was not enabled by default, I guess. Thanks again!

**Comment by helmo** [comment]
Thanks... and sorry about the symlinks change ... I didn't notice it was a different command, and don't have it installed.

**Pull request merged**
